# Riduzione dataset #

In [0]:
import numpy as np
import pandas as pd
import string
import itertools
import matplotlib.pyplot as plt

products = pd.read_csv("products_clean.csv")
reviews = pd.read_csv("reviews_clean.csv")

setCategories = ["music", "musical-instruments", "books", "english-books", "dvd", "videogames"]

Voglio trovare il numero di prodotti per categoria

In [0]:
numProducts = pd.DataFrame()

numProducts["Categoria"] = setCategories

listCount = []
for cat in setCategories:
    count = 0
    for pcat in products.category:
          if (cat == pcat):
            count = count + 1
    listCount.append(count)
    
numProducts["num_prodotti"] = listCount

In [0]:
numProducts

             Categoria  num_prodotti
0                music           672
1  musical-instruments           601
2                books           993
3        english-books           873
4                  dvd           616
5           videogames           558

In [0]:
prodDataset = pd.DataFrame()

prodDataset["Categoria"] = list(products.category)
prodDataset["product"] = list(products._id)

In [0]:
result = pd.merge(prodDataset, reviews)

In [0]:
listCount2 = []
for cat in setCategories:
    count2 = 0
    for rcat in result.Categoria:
          if (cat == rcat):
            count2 = count2 + 1
    listCount2.append(count2)
    
numProducts["num_recensioni"] = listCount2

In [0]:
numProducts

             Categoria  num_prodotti  num_recensioni
0                music           672           15251
1  musical-instruments           601           29391
2                books           993           36035
3        english-books           873           10731
4                  dvd           616           28549
5           videogames           558           40097